apiVersion: infra.nephio.org/v1alpha1
kind: Network
metadata:
  name: vpc-test
spec:
  topology: nephio
  routingTables:
  - name: vpc-test
    prefixes:
    - prefix: 10.0.0.0/24
    interfaces:
    - kind: bridgedomain
      bridgeDomainName: vpc-test
  bridgeDomains: 
  - name: vpc-test
    interfaces:
    - kind: interface
      selector:
        matchExpressions:
        - {key: nephio.org/cluster-name, operator: Exists}
      attachmentType: vlan
